find_package(Qt5 HINTS $ENV{QT_DIR} COMPONENTS REQUIRED Core Widgets)

set(CMAKE_POLICY_DEFAULT_CMP0100 NEW)
cmake_policy(SET CMP0100 NEW)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

set(Qt5_BIN_DIR $ENV{QT_DIR}/../../bin)
